#!/usr/bin/env python3
"""Generate a PyInstaller --version-file (Windows VERSIONINFO) from the
package version, so the exes show proper product/company/version metadata in
file properties (helps both users and AV/SmartScreen heuristics)."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from usbferry import __version__  # noqa: E402

def vs_version() -> tuple[int, ...]:
    parts = []
    for p in __version__.split(".")[:4]:
        try:
            parts.append(int(p))
        except ValueError:
            parts.append(0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts)

v = vs_version()

TEMPLATE = f"""# generated by tools/make_version_info.py - do not edit
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v},
    prodvers={v},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'usbferry project'),
        StringStruct('FileDescription', 'usbferry - share USB devices and LAN over the internet'),
        StringStruct('FileVersion', '{__version__}'),
        StringStruct('InternalName', 'usbferry'),
        StringStruct('LegalCopyright', 'MIT License - https://github.com/ALeXXBody/usbferry'),
        StringStruct('OriginalFilename', 'usbferry.exe'),
        StringStruct('ProductName', 'usbferry'),
        StringStruct('ProductVersion', '{__version__}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""

out = ROOT / "build" / "version-info.txt"
out.parent.mkdir(exist_ok=True)
out.write_text(TEMPLATE)
print(f"wrote {out} for version {__version__}")
